### ISSUE TITLE
Recollir i emmagatzemar metadades de Dynamic Web Twain

### ISSUE THREAD

**Issue by scalafat-dgtic** [GovernIB/digitalib#102]
En relació a [DWT: Enviament metadades de document escanejat](https://github.com/GovernIB/pluginsib-scanweb/issues/15).

1. Recollir aquestes metadades de l'escaneig de documents electrònics en paper.
2. Emmagatzemar-les a l'aplicació per poder recuperar-les

**Comment by anadal-fundaciobit** [comment]
S'ha creat una nova taula per guardar les metadades i un nou camp a pfi_transaccio per guardar el PAPER_SIZE.
També s'ha creat un document de migració de versions.

Via web es va decidir no donar més informació a part de la bàsica o sigui que els nous camps i metadades nop es mostren. Aqui on es veuen és en lAPI ScanWeb Simple:

![imatge](https://user-images.githubusercontent.com/17084256/78775309-4e10ca80-7996-11ea-9cce-5e2ee3455369.png)
