### ISSUE TITLE
ApiScanWebSimple: Afegir metadades

### ISSUE THREAD

**Issue by scalafat-dgtic** [GovernIB/digitalib#103]
L'ApiScanWebSimple ja conté camps com pixelType, pppResolution, formatFile i ocr dins la classe ScanWebSimpleScannedFileInfo. 

Per els següents camps:
1. Metadades d'un document electrònic [annex I de la Resolució](https://www.boe.es/boe/dias/2011/07/30/pdfs/BOE-A-2011-13169.pdf) 
2. Metadades de la NTI de digitalització de documents que indica la [Guia de aplicació de digitalizació de documents](https://www.hacienda.gob.es/Documentacion/Publico/SGT/CATALOGO_SEFP/284_11.Guia%20de%20aplicacion%20de%20digitalizacion%20(acc).pdf) en la pàgina 17, punt 40

Es pot utilitzar el camp additionalMetadatas, que es un list de clau-valor,  de la classe ScanWebSimpleFormMetadatas.

**Comment by anadal-fundaciobit** [comment]
S'ha implementat en el ISSUE #102
