### ISSUE TITLE
Enviament de metadades d'escaneig a l'Arxiu

### ISSUE THREAD

**Issue by scalafat-dgtic** [GovernIB/digitalib#106]
Atès que ja es guarda la informació de les metadades de l'escaneig dins Base de Dades, a la taula Transacció, enviar a l'Arxiu junt amb la resta de metadades.
- eni:resolucion - INFOSCANRESOLUCIOPPP
- eni:idioma (del document) - SIGNPARAMLANGUAGEDOC
- eni:profundidad_color - INFOSCANPIXELTYPE

**Comment by anadal-fundaciobit** [comment]
Aquí teniu les noves metadades que s'envien dins les metadades. NOTA: id_origen i subtipo es varen posar  a pinyo fix en les proves. En producció sortiran buides.


![imatge](https://user-images.githubusercontent.com/17084256/81275417-f4152a80-9051-11ea-97f0-ae48b044da55.png)
