### ISSUE TITLE
Enviament metadades CSV i id_tramite a Arxiu @O_A_E @DGMAD-Arxiu

### ISSUE THREAD

**Issue by scalafat-dgtic** [GovernIB/digitalib#110]
Actualment, les metadades següents s'envien amb valors incorrectes:
- eni:def_csv. Ha d'enviar una URL on es defineixi el procediment de generació de CSVs.
- eni:id_tramite. Ha d'enviar una codificació que indiqui el codi SIA corresponent

Hem demanat a la OAE quins són els valors correctes que s'han d'emmagatzemar a l'Arxiu

**Comment by anadal-fundaciobit** [comment]
La part tècnica ja està llesta. Falta que OAE crei el document de definicio de CSV i que les APPs enviïn informació de tràmitid o procedimentid SIA.

**Comment by anadal-fundaciobit** [comment]
Amb Document Custody d'Arxiu CAIB ja funciona:

![imatge](https://user-images.githubusercontent.com/17084256/81652232-b3435a00-9433-11ea-8caf-97c2724fcc4c.png)

**Comment by anadal-fundaciobit** [comment]
S'ha fet el commit. Estam pendent de que arxiu funcioni. Quan funcioni, provarem i si va llavors es pot tancar aquest issue.

**Comment by oae** [comment]
Hi, is it possible for you to not tag me in the commit messages? :)

**Comment by anadal-fundaciobit** [comment]
Faltaven darreres proves i condició de quan enviar origen_id. Tambe s'ha actualitzat la versió de l'API i del Plugin d'ArxiuCaib
