### ISSUE TITLE
Emmagatzemar metadades restants (id_origen i tamano_logico) cap a Arxiu @DGMAD

### ISSUE THREAD

**Issue by scalafat-dgtic** [GovernIB/digitalib#111]
Apart de les mencionades a #106 i #110, es vol que DigitalIB emmagatzemi a Arxiu les següents metadades restants:
- eni:id_origen. El seu valor ja es troba emmagatzemat al camp Id (pk). Sabent que el valor estarà duplicat, millor no deixar-la en blanc.
- eni:tamano_logico. Mida del document

PD: Eliminar tamany_fisic de les metadades !!!!

**Comment by anadal-fundaciobit** [comment]
* eni:tamano_logico: Aquesta ja es va fer a la ISSUE #106 
* eni:id_origen: ha de tenir un  tenir un format  ES_<Órgano>_<AAAA>_<ID_específico> però hi ha dues petites característiques:
       (1) Segons l'API Arxiu, els òrgans associats a un expedient o document poden ser N (una llista). Pel format anterior s'ha obtingut el primer òrgan de la llista. Si no hi ha òrgans llavors no es defineix l'id_origen
      (2) ID_específico en principi hauria de contenir l'ID de la transacció, però aquesta es pot repetir entre aplicacions per això aquest id esta format per <PREFIX_APP><ID_TRANSACCIO>

Un exemple es mostra a continuació:

![imatge](https://user-images.githubusercontent.com/17084256/81383683-b1665780-9110-11ea-8f8e-ad3346dd502f.png)
