### ISSUE TITLE
Anàlisi desenvolupament de Separador de Documents @DGMAD

### ISSUE THREAD

**Issue by scalafat-dgtic** [GovernIB/digitalib#112]
Tasca associada a la divisió de la tasca original del Desenvolupament del Separador en 'issues' més petits.

**Comment by anadal-fundaciobit** [comment]
Enviada primera proposta a Simó i Salvador.

**Comment by scalafat-dgtic** [comment]
Es consensuen els diferents requeriments entre Fundació Bit, DGMAD i OAE i es prepara per el desenvolupament.

S'adjunta la proposta número 4.
[AnalisiSeparadorsV4.pdf](https://github.com/GovernIB/digitalib/files/4836662/AnalisiSeparadorsV4.pdf)
