### ISSUE TITLE
Desenvolupament digitalització massiva de documents

### ISSUE THREAD

**Issue by scalafat-dgtic** [GovernIB/digitalib#113]
Segons #112, es proposa el desenvolupament de la digitalització massiva de documents tenint en compte les limitacions consensuades i poguent-les especificar en les propietats globals de l'aplicació. Per exemple, limitació de la mida del document de 15MB per @_firma

[AnalisiSeparadorsV4.pdf](https://github.com/GovernIB/digitalib/files/5193798/AnalisiSeparadorsV4.pdf)

**Comment by anadal-fundaciobit** [comment]
Falta la conformitat de la DGMAD. Per ara ho tancam i reobrirem nous issues per canvis puntuals.
