### ISSUE TITLE
Crear un sistema d'avisos per a incidències

### ISSUE THREAD

**Issue by scalafat-dgtic** [GovernIB/digitalib#114]
Estaria bé comptar amb un sistema de creació de avisos per notificar als usuaris de les possibles incidències en el sistema.
Per exemple:
- Des del backoffice, configurar un avís, que aparegui en la pantalla inicial, de que hi ha problemes de sobrecàrrega temporals durant el procés de firma.

Aquesta tasca implica:
- Creació de taula de BD d'Avisos amb els camps TIPUS_AVIS, DESCRIPCIO, DATA_INICI, DATA_FI, CONFIGURACIO_GRUP (FK)

**Comment by anadal-fundaciobit** [comment]
Modificacions a la taula d'avisos:
    (1) S'afegirà un perfil a la taula d'avisos
    (2) Data Inici, data Fi, Perfil i configuració de grup seran elements opcionals (nullable)
    (3) S'afegirà un booleà indicant si es bloqueja l'accés a la configuració de grup  i/o al perfil.

**Comment by scalafat-dgtic** [comment]
S'han destacat els textos dels avisos.

S'aprofita per modificar el persistence.xml per afegir les propietats "show_sql" i "format_sql"
