### ISSUE TITLE
En digitalIB tenir en compte el tema del tipus de Còpia

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/digitalib#118]
Bon dia, ,
Arran de la reunió d'ahir amb l'OAE convé tenir present que la funcionalitat de digitalització massiva també ha de contemplar que únicament usuaris amb rols DIB_USER podran especificar "Còpia Autèntica" com estat de elaboració. Els que no tinguin el rol només podran indicar "Còpia"
Endmés també ha de desapareix "Original" com a valor seleccionable en el desplegable.
Només perquè ho tinguis en compte.

Salutacions,

**Comment by scalafat-dgtic** [comment]
Entenc que el comportament descrit és en el cas exclusiu de Regweb i que són ells qui fan les comprovacions de si els funcionaris tenen, o no, el rol DIB_USER.
El tanc, no correspon a DigitalIB. I més tenint en compte, que en l'escaneig massiu l'estat d'elaboració el controla l'aplicació client.
