### ISSUE TITLE
Emmagatzemar el codi DIR3 del funcionari habilitat que fa la còpia

### ISSUE THREAD

**Issue by scalafat-dgtic** [GovernIB/digitalib#125]
Es vol poder emmagatzemar el codi DIR3 del funcionari habilitat, tant a través de Digitalització com a través de l'API de còpia autèntica.

Per fer-ho, es preveu integrar DigitalIB amb DIR3Caib:

- Digitalització, es proposa incorporar-ho com una columna nova de l'Usuari-Persona, obligatòria:

![image](https://user-images.githubusercontent.com/44995350/110122516-03731a80-7dc0-11eb-99e9-647da485c97d.png)

- Còpia Autèntica: poder recollir, per part de l'Usuari-Aplicació, la informació sobre DIR3Caib i emmagatzemar-la a BD en la transacció. És probable que requereixi integració amb les aplicacions sol·licitants com REGWEB i l'UDIR

**Comment by anadal-fundaciobit** [comment]
Solucionat. 

![imagen](https://user-images.githubusercontent.com/17084256/116038233-79318f00-a669-11eb-9c48-2535eb968bf6.png)
