### ISSUE TITLE
Poder treure estadístiques sobre transaccions a BD de PRO

### ISSUE THREAD

**Issue by scalafat-dgtic** [GovernIB/digitalib#126]
Tot i que ja es té informació sobre les transaccions a BD, des de l'OAE ens demanaran periòdicament dades estadístiques sobre les transaccions efectuades, tant a nivell de Digitalització com de còpia autèntica.

Amb l'objectiu de reduir el número de CAIs a realitzar periòdicament a Base de Dades. Es proposen dues solucions:
- Crear una vista, des del back, que permeti treure la informació conjunta bàsica de les transaccions (especialment per fer analitzar l'ús de REGWEB). Si es pot modificar, millor. Ex de la informació a mostrar:

_select t.transaccioid, t.funcionariusername, u.username, f.nom, f.tamany as "Mida (bytes)", DECODE(t.infoscanpixeltype, 1,'B/N',8,'Gris',32,'Color') as "Color?", t.infoscanresolucioppp as "Resolució", t.infoscanpapersize, t.infoscandatacaptura
from dib_transaccio t, dib_fitxer f, dib_usuariaplicacio u
where t.fitxersignaturaid = f.fitxerid and u.usuariaplicacioid = t.usuariaplicacioid and t.usuariaplicacioid = XXXX
order by t.infoscandatacaptura DESC_

- Crear una secció o mòdul que permeti fer consultes SQL a BD de PRO. S'hauria de mirar si a nivell d'estàndards això es pot fer o no.

**Comment by anadal-fundaciobit** [comment]
![imagen](https://user-images.githubusercontent.com/17084256/116193326-78fbc700-a72f-11eb-9ced-e1da229ed347.png)
![imagen](https://user-images.githubusercontent.com/17084256/116193355-81540200-a72f-11eb-96fa-03c412a8478d.png)
![imagen](https://user-images.githubusercontent.com/17084256/116193383-8d3fc400-a72f-11eb-8543-ba3c41aa49dd.png)

**Comment by anadal-fundaciobit** [comment]
Solucionat.

**Comment by anadal-fundaciobit** [comment]
Refer Estadistiques:
1. Separa estadistiques de persones i d'aplicacions
2. Afegir a filtres funcionari username, usuari aplicacio i usuari persona
3. Afegir columna transacció multiple
4. Agrupar i filtrar per tipus de transacció i per configuracio
