### ISSUE TITLE
Canviar la firma de DIGITALIB per fer servir la de PORTAFIB

### ISSUE THREAD

**Issue by scalafat-dgtic** [GovernIB/digitalib#131]
A DIGITALIB ens han fet notar que la firma s'efectua amb un algorisme SHA-1.

![image](https://user-images.githubusercontent.com/44995350/116363840-d82b0b80-a803-11eb-9b24-cad3fbccb1a7.png)

Segons la política de firma de l'Estat (https://administracionelectronica.gob.es/ctt/resources/Soluciones/239/Descargas/Perfiles-de-certificados-electronicos-2-0.pdf?idIniciativa=239&idElemento=7073) s'indica que:
"Actualmente, en dichas guías se recomienda utilizar como mínimo, el algoritmo de firma SHA2withRSA tanto en los certificados de las raíces y subraíces como en los certificados de entidades finales. **Se prohíbe el uso de SHA-1**, recomendando SHA256 o SHA512 para todos los certificados. Es obligatorio el uso de al menos SHA256 para los certificados de sitios web finales emitidos con posterioridad al 1 de Enero de 2016 y para todos los certificados de sitio web a partir del 1 de Enero de 2017. En cuanto al uso de longitudes de clave RSA, la mencionada norma establece la posibilidad de utilizar RSA a 2048 para entidades finales y 4096 para raíces y subraíces"

Per tant, es demana:

- Afegir com a firma de DIGITALIB l'emprada per PORTAFIB així com ho fan altres aplicacions.
- En cas de no poder fer-ho ràpidament, canviar l'algorisme de SHA-1 a SHA-256.

**Comment by anadal-fundaciobit** [comment]
Ja es va fer a "Implementar API Firma Simple en Servidor #133 "
