### ISSUE TITLE
Falta camp eni:organo al enviar fitxer a Arxiu

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/digitalib#135]
Apareix el següent error al fer una digitalització que s'envia a Arxiu:

2021-05-05 12:59:56,926 ERROR [STDERR] (http-10.215.29.9-18080-13) es.caib.plugins.arxiu.caib.ArxiuCaibException: [HTTP_500, COD_021] eni:organo is required in the node

**Comment by anadal-fundaciobit** [comment]
Solucionat el problema, però ara em dona el següent error. L'he comentat a SIMO i mirarà de parlar amb toni gaya a veure que passa.

![imagen](https://user-images.githubusercontent.com/17084256/117295161-ca186300-ae73-11eb-821c-2c8210a3d9d9.png)

**Comment by scalafat-dgtic** [comment]
Se solventen els errors amb @firma DES i, per tant, ja no apareixen els errors esmentats.
