### ISSUE TITLE
Dades Obertes - Desenvolupament API REST de consulta de dades d'ús de DigitalIB

### ISSUE THREAD

**Issue by scalafat-dgtic** [GovernIB/digitalib#142]
Des de Dades Obertes ens comuniquen que totes les aplicacions que tenguin dades susceptibles de ser publicades al portal de Dades Obertes han de tenir una API REST pública per a la seva consulta.

Es vol, llavors, que DigitalIB tengui una API REST perquè el Portal de Dades Obertes pugui consultar-ne l'ús de l'aplicació. A priori, a falta de definir la informació que ha de tornar DigitalIB, es demana que tengui un retorn de les dades similars a #126

**Comment by anadal-fundaciobit** [comment]
![imagen](https://user-images.githubusercontent.com/17084256/158786491-5b745180-7dfe-4c39-9adc-4e0cf665585c.png)

![imagen](https://user-images.githubusercontent.com/17084256/158786534-91278c3b-878b-42fd-9906-55f7848b0e64.png)

**Comment by anadal-fundaciobit** [comment]
Solucionat

**Comment by anadal-fundaciobit** [comment]
Per tant, deixaríem:

-     "transaccioID"
-     "transaccioMultiple"
-     "funcionariUsername"
-     "appname"
-     "fitxerMidaBytes"
-     "color"
-     "resolucio"
-     "midaPaper"
-     "dataCapturaISO8601"
-     "estat" (tots)
-     codiDir3
-     entitat (o configuracióGrup)
-     idioma del document
-     duplex
-     missatgeError
-     origen
-     DocumentTipus (Tipus Documental TD)
-    "usrname"

**Comment by anadal-fundaciobit** [comment]
Solucionat. Actualitzat també digitalib.fundaciobit.org
