### ISSUE TITLE
Canvis en DigitalIB Massiu des de Plugin de Escaneig

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/digitalib#151]
(1) No permetre custòdia des de Plugin de Escaneig de DigitalIB massiu: això ve a causa que el plugin d'escaneig només inclou un sol estat i qualsevol error invalida totes les subtransaccions. Però el procés d'Arxiu no es pot revertir, per això no l'hem de permetre des de Plugin d'ScanWeb de DigitalIB Massiu

(2)  En el PLugin de ScanWeb de digitalIB s'han de revisar l'estat de totes les subtransaccions. Si alguna d'elles ha fallat s'ha de donar el procés d'escaneig per invalid.

![imagen](https://user-images.githubusercontent.com/17084256/127646203-17de0e46-736a-417c-a769-be1b6710c872.png)

**Comment by scalafat-dgtic** [comment]
Ja resolt
