### ISSUE TITLE
Estudi de DigitalIB Massiu en entorn WEB

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/digitalib#153]
Actualment, el digitalIB només està disponible a traves de l'API Massive ScanWEB Simple i Plugin ScanWeb DigitalIB Massiu.

Estudiar la possibilitat de permetre scanwebmassiu en entorn WEB de DigitalIB.

**Comment by scalafat-dgtic** [comment]
duplicat #175
