### ISSUE TITLE
Pàgina d'inici - Fer pantalla completa

### ISSUE THREAD

**Issue by scalafat-dgtic** [GovernIB/digitalib#16]
Si no té major utilitat, treure el menú de la pàgina d'inici de l'aplicació perquè té opcions redundants i ocupa espai.

**Comment by anadal-fundaciobit** [comment]
Problemes amb un perfil "Administrador"


![imatge](https://user-images.githubusercontent.com/17084256/51838222-f690bc80-2305-11e9-9962-d328a81a5942.png)

**Comment by scalafat-dgtic** [comment]
El nou comportament és el següent:
- Si hi ha pipella d'inici --> L'entrada a l'aplicació va a la pipella d'inici
- Si no hi ha pipella d'inici -->
    Si és USER --> va a pipella d'Usuari
    Si és ADMIN --> va a pipella d'Admin
    Si és USER i ADMIN --> va a pipella d'Usuari

**Comment by scalafat-dgtic** [comment]
Si deixam l'aplicació sense pipella d'inici ja satisfà el requisit inicial. Tancam
