### ISSUE TITLE
Adaptar comportament DigitalIB a digitalització massiva

### ISSUE THREAD

**Issue by scalafat-dgtic** [GovernIB/digitalib#203]
Actualment,a l'hora de començar una transacció, se'ns demana, entre d'altres, la següent informació:

![image](https://user-images.githubusercontent.com/44995350/235083603-8cd92a9a-50ea-4c98-b488-bc8df861387e.png)
(fixem-nos que es demanen les metadades d'un sol document)

però després, a l'hora de fer escanejos permetem fer la digitalització massiva de documents (que posen ser N). Per tant, es crea una incongruència entre que demanam informació d'un sol document, però després en podem incorporar molts de diferents, i així queda reflectit posteriorment a l'Arxiu (un sol conjunt de metadades assignat a tota la transacció amb N documents, quan tocaria enviar conjunts de metadades separats per cada document).

Es demana, doncs, revisar el comportament amb l'objectiu d'imitar que es duu a terme al plugin de DigitalIB a REGWEB on es puguin determinar les metadades per cada document de la transacció, per tal de que quedin diferenciats dins l'Arxiu.

**Comment by anadal-fundaciobit** [comment]
Ara es demanen les dades als tres perfils ( NOMES SCAN, SCAN+FIRMA i SCAN+FIRMA+ARXIU).
L'idioma del document es posava per defecte a l'idioma de la UI, cosa que estava malament. S'ha llevat el per defecte i ara en els tres perfils demana aquesta informació en el POST-ESCANEIG.
