### ISSUE TITLE
Dades Obertes - Ordenació dels camps

### ISSUE THREAD

**Issue by scalafat-dgtic** [GovernIB/digitalib#225]
Des de Dades Obertes ens donen vistiplau a la pujada a PRO però ens sol·liciten una millora que pot anar a la següent versió:

"Proposam una millora, que els camps de paginació vagin per damunt el camp "resultat" que conté la llista de transaccions. D'aquesta manera queden visibles sempre tot i que la llista de "resultat" es desplegui."

**Comment by anadal-fundaciobit** [comment]
S'ha fet el que deia i a més s'ha adaptat al darrer document de Normatives de DadesObertes.
