### ISSUE TITLE
Ofuscar logs 

### ISSUE THREAD

**Issue by scalafat-dgtic** [GovernIB/digitalib#242]
Els logs del mètode signUsingApiFirmaSimple d'ApiFirmaSimpleLogicaEJB (a partir de la línia 85) mostra informació compromesa en INFO. Es sol·licita passar a DEBUG (actualment no puc compilar DigitalIB per errors en les dependències).

**Comment by anadal-fundaciobit** [comment]
Solucionat problema de compilació a  https://github.com/GovernIB/digitalib/issues/243
