### ISSUE TITLE
Administrador - Modificar pantalla Usuaris Persona

### ISSUE THREAD

**Issue by scalafat-dgtic** [GovernIB/digitalib#246]
La OAE ens demana modificar la pantalla d'Usuaris Persona afegint filtres per:
- Username
- Llinatges

i afegir opcions per poder **exportar els resultats a fulls de càlcul** (excel, calc, etc)

![image](https://github.com/user-attachments/assets/73782605-ac23-44af-a0e9-b029171a8093)

**Comment by anadal-fundaciobit** [comment]
Solucionat.
![imatge](https://github.com/user-attachments/assets/6a5c3b84-7571-4132-9845-bd487f9e7601)
