### ISSUE TITLE
Arreglar llistat de Transaccions (Persona i Aplicacio)

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/digitalib#29]
(A) En el menu d'Administrador existeixen dues gestions de les transaccions: una de Persones i l'altre d'Aplicacions. S'han de realitzar un conjunt de millores:

(1) Titol List i Form: Afegir la paraula Aplicacio i Persona segons el tipus (isUtilitzatPerAplicacio()).
(2) Substituir "ID Transaccio Web" per "TransaccioID"
(3) En postList() reemplaçar UsuariAplicacio pel nom corresponent (Pot ser seria interessant convertir-ho en un combobox i fer un reference list a UsuariAplicacio. NOTA: Controlar Null)
(4) En "groupBy"  llevar usuariAplicacio o UsuariPersona segons el valor de isUtilitzatPerAplicacio(). En filterForm, **copiar** el groupByDefault a groupby i d'aquest darrer eliminar un o l'altre
(5) Mostrar Nom i poder fer cerques per aquest

(B) En llistat de transaccions del menú de Usuari, ocultar columna i groupby "usuari  Persona"

Tot això s'ha d'intentar fer en les classes Pare més llunyanes amb la finalitat que afecti al major nombre de subclasses (AbstractTransaccioController)

**Comment by scalafat-dgtic** [comment]
**PENDENT DE PUJAR**
(A) En el menu d'Administrador existeixen dues gestions de les transaccions: una de Persones i l'altre d'Aplicacions. S'han de realitzar un conjunt de millores:

**FET** (1) Titol List i Form: Afegir la paraula Aplicacio i Persona segons el tipus (isUtilitzatPerAplicacio()).
(2) Substituir "ID Transaccio Web" per "TransaccioID"
(3) En postList() reemplaçar UsuariAplicacio pel nom corresponent (Pot ser seria interessant convertir-ho en un combobox i fer un reference list a UsuariAplicacio. NOTA: Controlar Null)
**EN PROCÉS** (4) En "groupBy" llevar usuariAplicacio o UsuariPersona segons el valor de isUtilitzatPerAplicacio(). En filterForm, copiar el groupByDefault a groupby i d'aquest darrer eliminar un o l'altre
**FET** (5) Mostrar Nom i poder fer cerques per aquest

(B) En llistat de transaccions del menú de Usuari, ocultar columna i groupby "usuari Persona"

Tot això s'ha d'intentar fer en les classes Pare més llunyanes amb la finalitat que afecti al major nombre de subclasses (AbstractTransaccioController)

**Comment by scalafat-dgtic** [comment]
Parts fetes, pujades.

(A) En el menu d'Administrador existeixen dues gestions de les transaccions: una de Persones i l'altre d'Aplicacions. S'han de realitzar un conjunt de millores:

**FET** (1) Titol List i Form: Afegir la paraula Aplicacio i Persona segons el tipus (isUtilitzatPerAplicacio()).
**FET** (2) Substituir "ID Transaccio Web" per "TransaccioID"
**EN PROCÉS** (3) En postList() reemplaçar UsuariAplicacio pel nom corresponent (Pot ser seria interessant convertir-ho en un combobox i fer un reference list a UsuariAplicacio. NOTA: Controlar Null)
**FET** (4) En "groupBy" llevar usuariAplicacio o UsuariPersona segons el valor de isUtilitzatPerAplicacio(). En filterForm, copiar el groupByDefault a groupby i d'aquest darrer eliminar un o l'altre
**FET** (5) Mostrar Nom i poder fer cerques per aquest

**FET** (B) En llistat de transaccions del menú de Usuari, ocultar columna i groupby "usuari Persona"

Tot això s'ha d'intentar fer en les classes Pare més llunyanes amb la finalitat que afecti al major nombre de subclasses (AbstractTransaccioController)

**Comment by scalafat-dgtic** [comment]
(A) En el menu d'Administrador existeixen dues gestions de les transaccions: una de Persones i l'altre d'Aplicacions. S'han de realitzar un conjunt de millores:

**FET** (1) Titol List i Form: Afegir la paraula Aplicacio i Persona segons el tipus (isUtilitzatPerAplicacio()).
**FET** (2) Substituir "ID Transaccio Web" per "TransaccioID"
**FET** (3) En postList() reemplaçar UsuariAplicacio pel nom corresponent (Pot ser seria interessant convertir-ho en un combobox i fer un reference list a UsuariAplicacio. NOTA: Controlar Null)
**FET** (4) En "groupBy" llevar usuariAplicacio o UsuariPersona segons el valor de isUtilitzatPerAplicacio(). En filterForm, copiar el groupByDefault a groupby i d'aquest darrer eliminar un o l'altre
**FET** (5) Mostrar Nom i poder fer cerques per aquest

**FET** (B) En llistat de transaccions del menú de Usuari, ocultar columna i groupby "usuari Persona"

Tot això s'ha d'intentar fer en les classes Pare més llunyanes amb la finalitat que afecti al major nombre de subclasses (AbstractTransaccioController)
