### ISSUE TITLE
Un cop rebut fitxers generar hash

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/digitalib#42]
Al guardar fitxer escanejat i fitxer signat, s'ha de generar el hash del fitxer i guardar-ho dins de la transacció.

**Comment by anadal-fundaciobit** [comment]
S'han de cercar els mètodes setFitxerEscanejatID() i setFitxerSignaturaIDi en aquests llocs calcular el HASH (poer exemple un MD5, cercar-ho per Internet) i ficar el valor obtingut a  setHashEscaneig() i  setHashFirma() respectivament.

**Comment by scalafat-dgtic** [comment]
S'ha colocat un SHA256 per major seguretat
