### ISSUE TITLE
Millores en Llistat d'Usuaris aplicació

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/digitalib#5]
(1) Modificar el títol per "Llistat d'Usuaris Aplicació"

(2) Afegir un enllaç cap al perfil (edicio) en llistat d'usuaris. Veure imatge:

![imatge](https://user-images.githubusercontent.com/17084256/48829089-b7784500-ed71-11e8-953f-4757c52f59ec.png)

**Comment by scalafat-dgtic** [comment]
Arreglats els enllaços a la edició dels perfils amb els canvis nous
