### ISSUE TITLE
Revisió OAE: Dades de les pantalles de Transacció, missatges de email i revisió de fitxers d'Arxiu

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/digitalib#65]
Queda que la gent den Josep digui com vol:
(1)  Pantalles de transaccions(que ha de mostrar-se als usuaris), 
(2) Missatges de email quan s'envia document o enllaç al document d'arxiu
(3) Si els fitxers estan guardats correctament dins Arxiu segons arxiver

------
- Deixar per defecte i no modificable l'opció del 'Document Estat Elaboració' a EE03 en fer una còpia autèntica.
- Ocultar metadades de "Ciutadà NIF" i "Ciutadà Nom" a pantalla per fer còpia autèntica

**Comment by scalafat-dgtic** [comment]
**FET** * Deixar per defecte i no modificable l'opció del 'Document Estat Elaboració' a EE03 en fer una còpia autèntica.
**FET** * Ocultar metadades de "Ciutadà NIF" i "Ciutadà Nom" a pantalla per fer còpia autèntica

**Comment by scalafat-dgtic** [comment]
- Simplificació botons obtenir còpies autèntiques a pipella usuari transaccions
- Incorporació botons obtenir còpies autèntiques a pipella admin transaccions
- S'oculta el botó de Cancel·lar a Configuració Usuari que duia a un 404
- Es modifica la documentació per compilació amb perfil CAIB de MAVEN

**Comment by scalafat-dgtic** [comment]
- S'afegeixen els botons per veure la informació de la firma, l'arxivat i els detalls de la transacció des del menú de l'usuari.

**Comment by scalafat-dgtic** [comment]
- Tornam enrera el moviment dels botons de 'Informació firma' i 'Informació arxivat'. Tornen a ser accessibles des del detall de la transacció.
- Petita millora d'estil
- Canvi en la navegació de les pantalles quan fan una còpia autèntica. Ara, en completar-la, mostra la llista de 'Les meves còpies autèntiques'

**Comment by scalafat-dgtic** [comment]
Per ara, queda així:
- La OAE dóna el vistiplau a les pantalles de Transaccions i la seva navegació. Quan s'acabi una transacció de Còpia Autèntica, a la CAIB, tornarà al llistat de Còpies Autèntiques.
- No s'han queixat del missatge de email. S'envia una referència a l'enllaç de ConCSV on es poden descarregar les versions original i imprimible
- No hi ha hagut queixa de l'arxiver.
