### ISSUE TITLE
Documentació Mínima digitalib-1.0.0: Manual de Integració emprant REST. 

### ISSUE THREAD

**Issue by scalafat-dgtic** [GovernIB/digitalib#69]
S'ha de documentar un manual de Integració emprant REST. S'adjunten algun manuals d'exemple

[PINBAL_integracio.pdf](https://github.com/GovernIB/digitalib/files/2803140/PINBAL_integracio.pdf)
[ARXIU_integracio.pdf](https://github.com/GovernIB/digitalib/files/2803137/ARXIU_integracio.pdf)
[DISTRIBUCIO_integració.pdf](https://github.com/GovernIB/digitalib/files/2803138/DISTRIBUCIO_integracio.pdf)
[NOTIB_integracio.pdf](https://github.com/GovernIB/digitalib/files/2803139/NOTIB_integracio.pdf)

**Comment by anadal-fundaciobit** [comment]
Dins el directori DOC hi ha el maunal creat anomenta Manual_de_API_ScanWeb_Simple.odt
