### ISSUE TITLE
Assignar Configuració per defecte als nous usuaris

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/digitalib#72]
Quan un usuari entra per primera vegada a l'aplicació, no te assignat cap Configuració de Grup i és l'Administrador de DigitalIB que manualment n'hi ha d'assignar un. 
Afegir una propietat "es.caib.digitalib.configuraciodegrupperdefecte=<<ID>>" amb l'ID de la Configuració de Grup que desitgen que s'assigni per defecte al donar d'alta els nous usuaris.

**Comment by scalafat-dgtic** [comment]
A la DGTIC hem xerrat que ho deixarem com està. No posarem un grup per defecte.

El nou usuari demanarà permís per entrar a un grup determinat ja existent i l'Administrador l'hi concedirà.

**Comment by anadal-fundaciobit** [comment]
S'ha afegit una propietat següent:

      
      #es.caib.digitalib.configuraciogruppereefecteEL=<![CDATA[<#if userinfo?? && userinfo.username??><#if userinfo.username = "test">1078</#if><#if userinfo.username = "admin">1233</#if></#if>]]>
      es.caib.digitalib.configuraciogruppereefecteEL=
