### ISSUE TITLE
Obrir un dialeg per seleccionar correu i idioma d'enviament de correu

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/digitalib#79]
Actualment només es demana el correu, però faltaria pode definir l'idioma en que enviar-ho (actualment s'envia amb l'idioma de la IU).

Una solucio senzilla seria usar el mètode dialeg de jQuery: http://jsfiddle.net/Kuy8e/1/

**Comment by scalafat-dgtic** [comment]
A la tasca #81 s'ha modificat l'alert d'enviament de correu electrònic i s'ha substituït per un modal:

- S'ha modificat el modal de manera que accepti una llista de correus electrònics.
- També té un apartat per afegir-hi contingut dins el correu

**Comment by anadal-fundaciobit** [comment]
Solucionat !!!!
