### ISSUE TITLE
Problema amb Oracle 12

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/digitalib#86]
Pareix que  a la configuració actual no li agrada Oracle 12. 
Per fer que funcioni s'ha d'afegir la següent propietat dins del fitxer: digitalib\persistence\jta\src\main\resources\META-INF\persistence.xml

Es podira fer un profile de Maven que quan sigui caib, llavors afegeixi aquesta propietat dins persistence.xml.

**Comment by scalafat-dgtic** [comment]
No hem tornat a tenir problemes al respecte després de la creació del profile de la CAIB de Maven.
